version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: This is a raw data 
    tables:
      - name: product
        identifier: raw_gz_product
        description: This is a raw data for Production
      - name: sales
        identifier: raw_gz_sales
        description: This is a raw data for sales
      - name: ship
        identifier: raw_gz_ship
        description: This is a raw data for ship
