version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: This is a raw data 
    tables:
      - name: product
        identifier: raw_gz_product
        description: This is a raw data for Production
        columns:
          - name: products_id
            description: primary key of the table products_id
            tests:
                - unique
                - not_null
                
      - name: sales
        identifier: raw_gz_sales
        description: This is a raw data for sales
        tests:
          - unique:
             column_name: "(orders_id || '-' || pdt_id )"
      - name: ship
        identifier: raw_gz_ship
        description: This is a raw data for ship
        columns:
          - name: orders_id
            description: primary key for order table ship
            tests:
                - unique
                - not_null
                
                  
